spring:
  application:
    name: BrainBoost

  logging:
    level:
      root: WARN
      com.BrainBoost.BrainBoost: DEBUG

  datasource:
    url: jdbc:mysql://localhost:3306/BrainBoost?useSSL=false&serverTimezone=UTC
    username: root
    password: 2004Vit@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
